// src/components/Home.jsx


//components
import Code from './Code';
import Result from './Result';
import Header from './Header';

const Home = () => {
    document.documentElement.style.overflow = 'hidden';
    return (
        <>
            <Header />
            <Code />
            <Result />
        </>
    )
}

export default Home;

// src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    // Set overflow hidden on document element
    document.documentElement.style.overflow = 'hidden';
  }
}

<app-header></app-header>
<app-code></app-code>
<app-result></app-result>
