// src/components/Code.jsx
import { useContext } from 'react';

//components
import Editor from './Editor';

import { Box, styled } from '@mui/material';

import { DataContext } from '../Context/DataProvider';

const Container = styled(Box)`
    background-color: #6fd6d3;
    height: 50vh;
    display: flex;
    border: 1px solid #6fd6d3;
    border-radius : 5px
`

const Code = () => {

    const { html, css, js, setHtml, setCss, setJs } = useContext(DataContext);

    return (
        <Container>
            <Editor 
                language="xml"
                heading="HTML"
                value={html}
                onChange={setHtml}
                icon='/'
                color='#FF3C41'
            />
            <Editor 
                language="css"
                heading="CSS"
                value={css}
                onChange={setCss}
                icon='*'
                color='#0EBEFF'
            />
            <Editor 
                language="javascript"
                heading="JS"
                value={js}
                onChange={setJs}
                icon='( )'
                color='#FCD000'
            />
        </Container>
    )
}

export default Code;

// src/app/components/code/code.component.ts
import { Component, OnInit } from '@angular/core';
import { CodeEditorService } from '../../services/code-editor.service';

@Component({
  selector: 'app-code',
  templateUrl: './code.component.html',
  styleUrls: ['./code.component.css']
})
export class CodeComponent implements OnInit {
  html: string = '';
  css: string = '';
  js: string = '';

  constructor(private codeEditorService: CodeEditorService) { }

  ngOnInit() {
    // Subscribe to changes
    this.codeEditorService.html$.subscribe(html => this.html = html);
    this.codeEditorService.css$.subscribe(css => this.css = css);
    this.codeEditorService.js$.subscribe(js => this.js = js);
  }

  onHtmlChange(html: string) {
    this.codeEditorService.setHtml(html);
  }

  onCssChange(css: string) {
    this.codeEditorService.setCss(css);
  }

  onJsChange(js: string) {
    this.codeEditorService.setJs(js);
  }
}

<div class="container">
  <app-editor 
    language="xml"
    heading="HTML"
    [value]="html"
    (valueChange)="onHtmlChange($event)"
    icon="/"
    color="#FF3C41"
  ></app-editor>
  
  <app-editor 
    language="css"
    heading="CSS"
    [value]="css"
    (valueChange)="onCssChange($event)"
    icon="*"
    color="#0EBEFF"
  ></app-editor>
  
  <app-editor 
    language="javascript"
    heading="JS"
    [value]="js"
    (valueChange)="onJsChange($event)"
    icon="( )"
    color="#FCD000"
  ></app-editor>
</div>
