// src/app/components/result/result.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { CodeEditorService } from '../../services/code-editor.service';

@Component({
  selector: 'app-result',
  templateUrl: './result.component.html',
  styleUrls: ['./result.component.css']
})
export class ResultComponent implements OnInit, OnDestroy {
  src: string = '';
  private subscriptions: Subscription[] = [];

  constructor(private codeEditorService: CodeEditorService) { }

  ngOnInit() {
    // Subscribe to all code changes
    this.subscriptions.push(
      this.codeEditorService.html$.subscribe(() => this.updateSrc()),
      this.codeEditorService.css$.subscribe(() => this.updateSrc()),
      this.codeEditorService.js$.subscribe(() => this.updateSrc())
    );
  }

  ngOnDestroy() {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  updateSrc() {
    const html = this.codeEditorService.getHtml();
    const css = this.codeEditorService.getCss();
    const js = this.codeEditorService.getJs();

    this.src = `
      <html>
        <body>${html}</body>
        <style>${css}</style>
        <script>${js}</script>
      </html>
    `;
  }

  get hasContent(): boolean {
    return !!(this.codeEditorService.getHtml() || 
              this.codeEditorService.getCss() || 
              this.codeEditorService.getJs());
  }
}

<div class="container" [style.background]="hasContent ? 'transparent' : 'white'">
  <iframe 
    [srcdoc]="src"
    title="output"
    sandbox="allow-scripts"
    width="100%"
    height="100%"
  ></iframe>
</div>

// src/components/Result.jsx
import { useState, useEffect, useContext } from 'react';

import { DataContext } from '../Context/DataProvider';

import { Box, styled } from '@mui/material';

const Container = styled(Box)`
    height: 41vh;
`

const Result = () => {

    const [src, setSrc] = useState('');
    const { html, css, js } = useContext(DataContext);
    
    const srcCode = `
        <html>
            <body>${html}</body>
            <style>${css}</style>
            <script>${js}</script>
        </html>
    `

    useEffect(() => {
        const timeout = setTimeout(() => {
            setSrc(srcCode);
        }, 900);

        return () => clearTimeout(timeout);
    }, [html, css, js,srcCode])

    return (
        <Container style={html || css || js ? null : {background: 'white' }}>
            <iframe 
                srcDoc={src}
                title="output"
                sandbox="allow-scripts"
                // frameBorder="0"
                width="100%"
                height="100%"
            />    
        </Container>
    )
}

export default Result;
